// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKkco3PyrXXjaq8hRXNKD360rNvTEcu8',
    appId: '1:1078407302493:web:43cea9cb3672e9228cecb4',
    messagingSenderId: '1078407302493',
    projectId: 'flogo-gen',
    authDomain: 'flogo-gen.firebaseapp.com',
    storageBucket: 'flogo-gen.firebasestorage.app',
    measurementId: 'G-KKQRQHRMTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBriIPYvHt8KW5ljTnQotkIYdBKVnWTKFU',
    appId: '1:1078407302493:android:df4416e3c9d5a5458cecb4',
    messagingSenderId: '1078407302493',
    projectId: 'flogo-gen',
    storageBucket: 'flogo-gen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0R-zyShbo7wRQdlQ6SFWoUyDZCTnkuPI',
    appId: '1:1078407302493:ios:d0de1d3a04b5807d8cecb4',
    messagingSenderId: '1078407302493',
    projectId: 'flogo-gen',
    storageBucket: 'flogo-gen.firebasestorage.app',
    iosBundleId: 'com.rk.flogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0R-zyShbo7wRQdlQ6SFWoUyDZCTnkuPI',
    appId: '1:1078407302493:ios:d0de1d3a04b5807d8cecb4',
    messagingSenderId: '1078407302493',
    projectId: 'flogo-gen',
    storageBucket: 'flogo-gen.firebasestorage.app',
    iosBundleId: 'com.rk.flogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBKkco3PyrXXjaq8hRXNKD360rNvTEcu8',
    appId: '1:1078407302493:web:042f0b6da3c07a888cecb4',
    messagingSenderId: '1078407302493',
    projectId: 'flogo-gen',
    authDomain: 'flogo-gen.firebaseapp.com',
    storageBucket: 'flogo-gen.firebasestorage.app',
    measurementId: 'G-NYMXLPHQHR',
  );
}
